feat: enable sorting feature
savaspamuk/car_sale_website pull request #4
Opened 2024-01-18 14:15 UTC by savaspamuk

2024-01-25 09:13 UTC, annasvst requested changes

2024-01-25 09:13 UTC, annasvst commented on src/context/getCarList.jsx
Rename this file to ListProvider.jsx

2024-01-25 09:13 UTC, annasvst commented on src/context/getCarList.jsx
Take a look at this file: https://github.com/frontend-from-0/group240123-files/blob/master/Lesson38/my-app/src/modules/user/UserProvider.tsx
Try to update this Provider component similar to the UserProvider (combine the two contexts - for passing data though application (CarsContext) and for updating the data (CarsDispatchContext)) and use useReducer hook to do the updates

2024-01-25 11:00 UTC, savaspamuk commented on src/context/getCarList.jsx
Anna, I adapt my code to these code structure, but obviously I couldn't understand why I do this :) I will search it or watch some videos about it to understand better :)

2024-01-27 19:55 UTC, annasvst commented on src/context/ListProvider.jsx
Remove this file and all usages, only use CarsProvider to use and update cars data

2024-02-05 13:14 UTC, savaspamuk commented on src/context/ListProvider.jsx
I removed and tried to adapt to components, but when I clicked the Cars menu, I took an error that I couldn't understand.

2024-02-09 10:05 UTC, annasvst approved these changes

2024-02-09 10:05 UTC, annasvst commented on src/context/CarsProvider.jsx
> +  const getCars = async () => {
This should not be incide a provider, move it to any presentational React component

2024-02-09 10:05 UTC, annasvst commented on src/context/CarsProvider.jsx
> +    const response = await fetch("https://freetestapi.com/api/v1/cars");
This should not be incide a provider, move it to any presentational React component

2024-02-09 10:05 UTC, annasvst commented on src/context/CarsProvider.jsx
> +  const handleSort = async (event) => {
This should not be incide a provider, move it to any presentational React component.

2024-02-09 10:05 UTC, annasvst commented on src/context/CarsProvider.jsx
> +    const data = await response.json();
This should not be incide a provider, move it to any presentational React component

2024-02-09 10:05 UTC, annasvst commented on src/context/CarsProvider.jsx
> +  const setMakeModel = (makeModel) => {
This should not be incide a provider, move it to any presentational React component

2024-02-09 10:05 UTC, annasvst commented on src/context/CarsProvider.jsx
> +  const handleSearch = async (makeModel) => {
This should not be incide a provider, move it to any presentational React component

2024-02-09 10:05 UTC, merged